// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

// COMPONENT cardbg

lv_obj_t * ui_cardbg_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_cardbg;
    cui_cardbg = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_cardbg, 660);
    lv_obj_set_height(cui_cardbg, 380);
    lv_obj_set_x(cui_cardbg, 248);
    lv_obj_set_y(cui_cardbg, 5);
    lv_obj_set_align(cui_cardbg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_cardbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_cardbg, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_cardbg, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_cardbg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_cardbg, lv_color_hex(0x0F0E1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_cardbg, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_cardbg, lv_color_hex(0x0F0E1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_cardbg, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_cardbg, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_cardbg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_cardbg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_cardbg, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_cardbg, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_cardbg, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_cardbg, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_cardbg, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CARDBG_NUM);
    children[UI_COMP_CARDBG_CARDBG] = cui_cardbg;
    lv_obj_add_event_cb(cui_cardbg, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_cardbg, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_cardbg_create_hook(cui_cardbg);
    return cui_cardbg;
}

