// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

void ui_comp_button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_card_create_hook(lv_obj_t * comp)
{
}

void ui_comp_cardbg_create_hook(lv_obj_t * comp)
{
}

void ui_comp_percent_create_hook(lv_obj_t * comp)
{
}
