// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

// COMPONENT card

lv_obj_t * ui_card_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_card;
    cui_card = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_card, 423);
    lv_obj_set_height(cui_card, 316);
    lv_obj_set_align(cui_card, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_card, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_cardbg2;
    cui_cardbg2 = ui_cardbg_create(cui_card);
    lv_obj_set_width(cui_cardbg2, 200);
    lv_obj_set_height(cui_cardbg2, 130);
    lv_obj_set_x(cui_cardbg2, -3);
    lv_obj_set_y(cui_cardbg2, -23);

    lv_obj_t * cui_card_h;
    cui_card_h = lv_label_create(cui_cardbg2);
    lv_obj_set_width(cui_card_h, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_card_h, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_card_h, -30);
    lv_obj_set_y(cui_card_h, 58);
    lv_label_set_text(cui_card_h, "H1");
    lv_obj_set_style_text_color(cui_card_h, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_card_h, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_card_h, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(cui_card_h, 0);
    lv_obj_t * cui_card_text;
    cui_card_text = lv_label_create(cui_cardbg2);
    lv_obj_set_width(cui_card_text, lv_pct(151));
    lv_obj_set_height(cui_card_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_card_text, -27);
    lv_obj_set_y(cui_card_text, -7);
    lv_obj_set_style_text_color(cui_card_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_card_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_card_text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(cui_card_text, 1);
    lv_obj_t * cui_card_title;
    cui_card_title = lv_label_create(cui_cardbg2);
    lv_obj_set_width(cui_card_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_card_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_card_title, -29);
    lv_obj_set_y(cui_card_title, -32);
    lv_label_set_text(cui_card_title, "Title");
    lv_obj_set_style_text_color(cui_card_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_card_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_card_title, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(cui_card_title, 2);
    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CARD_NUM);
    children[UI_COMP_CARD_CARD] = cui_card;
    children[UI_COMP_CARD_CARDBG2] = cui_cardbg2;
    children[UI_COMP_CARD_CARDBG2_CARD_H] = cui_card_h;
    children[UI_COMP_CARD_CARDBG2_CARD_TEXT] = cui_card_text;
    children[UI_COMP_CARD_CARDBG2_CARD_TITLE] = cui_card_title;
    lv_obj_add_event_cb(cui_card, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_card, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_card_create_hook(cui_card);
    return cui_card;
}

