// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Charging = NULL;
lv_obj_t * ui_content_group5 = NULL;
lv_obj_t * ui_content5 = NULL;
lv_obj_t * ui_info_group5 = NULL;
lv_obj_t * ui_contact_icon5 = NULL;
lv_obj_t * ui_call_number5 = NULL;
lv_obj_t * ui_date5 = NULL;
lv_obj_t * ui_button5 = NULL;
lv_obj_t * ui_charging_time_group = NULL;
lv_obj_t * ui_charging_tme = NULL;
lv_obj_t * ui_Label1_charging = NULL;
lv_obj_t * ui_group1 = NULL;
lv_obj_t * ui_Label3_charging = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_charging_cost_group = NULL;
lv_obj_t * ui_charging_cost = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_group2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_charging_energie_group = NULL;
lv_obj_t * ui_charging_energie = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_group3 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_charging_speed_group = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_group4 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_charge_bar_group = NULL;
lv_obj_t * ui_cardbg3 = NULL;
lv_obj_t * ui_anim_bg2 = NULL;
lv_obj_t * ui_anim_bg3 = NULL;
lv_obj_t * ui_anim_bg1 = NULL;
lv_obj_t * ui_mask1 = NULL;
lv_obj_t * ui_mask2 = NULL;
lv_obj_t * ui_charge_bar = NULL;
lv_obj_t * ui_start_bar = NULL;
lv_obj_t * ui_start_bar_indicator = NULL;
lv_obj_t * ui_percent = NULL;
lv_obj_t * ui_charge_bar_indicator = NULL;
lv_obj_t * ui_percent_number1 = NULL;
lv_obj_t * ui_percent_number2 = NULL;
lv_obj_t * ui_percent1 = NULL;
lv_obj_t * ui_Label16 = NULL;
// event funtions
void ui_event_Charging(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_button5, 0);
        top_on_Animation(ui_charging_time_group, 0);
        top_on_Animation(ui_charging_cost_group, 100);
        top_on_Animation(ui_charging_energie_group, 200);
        bottom_on_Animation(ui_charging_speed_group, 100);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        bottom_off_Animation(ui_button5, 0);
        top_off_Animation(ui_charging_time_group, 100);
        top_off_Animation(ui_charging_cost_group, 50);
        top_off_Animation(ui_charging_energie_group, 0);
        bottom_off_Animation(ui_charging_speed_group, 100);
    }
}

void ui_event_button5_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_End, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_End_screen_init);
    }
}

// build funtions

void ui_Charging_screen_init(void)
{
    ui_Charging = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Charging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Charging, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group5 = lv_obj_create(ui_Charging);
    lv_obj_set_width(ui_content_group5, lv_pct(100));
    lv_obj_set_height(ui_content_group5, lv_pct(100));
    lv_obj_set_align(ui_content_group5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content_group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content5 = lv_obj_create(ui_content_group5);
    lv_obj_set_height(ui_content5, lv_pct(100));
    lv_obj_set_flex_grow(ui_content5, 1);
    lv_obj_set_align(ui_content5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group5 = lv_obj_create(ui_content5);
    lv_obj_set_width(ui_info_group5, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_info_group5, -11);
    lv_obj_set_y(ui_info_group5, -15);
    lv_obj_set_flex_flow(ui_info_group5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_info_group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon5 = lv_img_create(ui_info_group5);
    lv_img_set_src(ui_contact_icon5, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_contact_icon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number5 = lv_label_create(ui_info_group5);
    lv_obj_set_width(ui_call_number5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_call_number5, -13);
    lv_obj_set_y(ui_call_number5, -15);
    lv_obj_set_align(ui_call_number5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number5, "www.fusiontech.com.tw");
    lv_obj_set_style_text_color(ui_call_number5, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date5 = lv_label_create(ui_content5);
    lv_obj_set_width(ui_date5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date5, 21);
    lv_obj_set_y(ui_date5, -19);
    lv_obj_set_align(ui_date5, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date5, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_date5, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button5 = ui_button_create(ui_content5);
    lv_obj_set_width(ui_button5, 150);
    lv_obj_set_height(ui_button5, 40);
    lv_obj_set_x(ui_button5, 20);
    lv_obj_set_y(ui_button5, 15);
    lv_obj_set_align(ui_button5, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_bg_color(ui_button5, lv_color_hex(0xDB2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_button5, lv_color_hex(0xDB2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button5, lv_color_hex(0xD40000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_label_set_text(ui_comp_get_child(ui_button5, UI_COMP_BUTTON_BUTTON_LABEL), "Stop Charging");

    ui_charging_time_group = ui_cardbg_create(ui_content5);
    lv_obj_set_width(ui_charging_time_group, 140);
    lv_obj_set_height(ui_charging_time_group, 100);
    lv_obj_set_x(ui_charging_time_group, -16);
    lv_obj_set_y(ui_charging_time_group, 2);
    lv_obj_set_align(ui_charging_time_group, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_pad_left(ui_charging_time_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charging_time_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charging_time_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charging_time_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charging_tme = lv_obj_create(ui_charging_time_group);
    lv_obj_set_width(ui_charging_tme, lv_pct(171));
    lv_obj_set_height(ui_charging_tme, lv_pct(235));
    lv_obj_set_align(ui_charging_tme, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_charging_tme, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charging_tme, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charging_tme, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1_charging = lv_label_create(ui_charging_tme);
    lv_obj_set_width(ui_Label1_charging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1_charging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1_charging, 0);
    lv_obj_set_y(ui_Label1_charging, 7);
    lv_obj_set_align(ui_Label1_charging, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1_charging, "Charging time");
    lv_obj_set_style_text_color(ui_Label1_charging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1_charging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1_charging, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_group1 = lv_obj_create(ui_charging_tme);
    lv_obj_set_height(ui_group1, 54);
    lv_obj_set_width(ui_group1, lv_pct(87));
    lv_obj_set_x(ui_group1, 1);
    lv_obj_set_y(ui_group1, -11);
    lv_obj_set_align(ui_group1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_group1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3_charging = lv_label_create(ui_group1);
    lv_obj_set_height(ui_Label3_charging, 33);
    lv_obj_set_width(ui_Label3_charging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label3_charging, 12);
    lv_obj_set_y(ui_Label3_charging, 17);
    lv_obj_set_align(ui_Label3_charging, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label3_charging, "28");
    lv_obj_set_style_text_color(ui_Label3_charging, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3_charging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3_charging, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_group1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -13);
    lv_obj_set_y(ui_Label7, -9);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "MIN");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_charging_tme, 0);
    ui_charging_cost_group = ui_cardbg_create(ui_content5);
    lv_obj_set_width(ui_charging_cost_group, 140);
    lv_obj_set_height(ui_charging_cost_group, 100);
    lv_obj_set_x(ui_charging_cost_group, 0);
    lv_obj_set_y(ui_charging_cost_group, 0);
    lv_obj_set_align(ui_charging_cost_group, LV_ALIGN_TOP_MID);
    lv_obj_set_style_pad_left(ui_charging_cost_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charging_cost_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charging_cost_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charging_cost_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charging_cost = lv_obj_create(ui_charging_cost_group);
    lv_obj_set_width(ui_charging_cost, lv_pct(171));
    lv_obj_set_height(ui_charging_cost, lv_pct(237));
    lv_obj_set_align(ui_charging_cost, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_charging_cost, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charging_cost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charging_cost, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_charging_cost);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 7);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "Charging cost");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_group2 = lv_obj_create(ui_charging_cost);
    lv_obj_set_height(ui_group2, 38);
    lv_obj_set_width(ui_group2, lv_pct(100));
    lv_obj_set_x(ui_group2, 0);
    lv_obj_set_y(ui_group2, -15);
    lv_obj_set_align(ui_group2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_group2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_group2);
    lv_obj_set_height(ui_Label8, 34);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label8, 2);
    lv_obj_set_y(ui_Label8, -30);
    lv_obj_set_align(ui_Label8, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label8, "$34.25");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_charging_cost, 0);
    ui_charging_energie_group = ui_cardbg_create(ui_content5);
    lv_obj_set_width(ui_charging_energie_group, 140);
    lv_obj_set_height(ui_charging_energie_group, 100);
    lv_obj_set_x(ui_charging_energie_group, 16);
    lv_obj_set_y(ui_charging_energie_group, 2);
    lv_obj_set_align(ui_charging_energie_group, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_pad_left(ui_charging_energie_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charging_energie_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charging_energie_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charging_energie_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charging_energie = lv_obj_create(ui_charging_energie_group);
    lv_obj_set_width(ui_charging_energie, lv_pct(171));
    lv_obj_set_height(ui_charging_energie, lv_pct(236));
    lv_obj_set_align(ui_charging_energie, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_charging_energie, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charging_energie, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charging_energie, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_charging_energie);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 7);
    lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label9, "Energy delivered");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_group3 = lv_obj_create(ui_charging_energie);
    lv_obj_set_height(ui_group3, 72);
    lv_obj_set_width(ui_group3, lv_pct(99));
    lv_obj_set_align(ui_group3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_group3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_group3);
    lv_obj_set_height(ui_Label10, 23);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label10, 39);
    lv_obj_set_y(ui_Label10, 5);
    lv_obj_set_align(ui_Label10, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label10, "84.89");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_group3);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -16);
    lv_obj_set_y(ui_Label11, -1);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "kWh");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_charging_energie, 0);
    ui_charging_speed_group = ui_cardbg_create(ui_content5);
    lv_obj_set_height(ui_charging_speed_group, 28);
    lv_obj_set_width(ui_charging_speed_group, lv_pct(70));
    lv_obj_set_x(ui_charging_speed_group, -11);
    lv_obj_set_y(ui_charging_speed_group, 0);
    lv_obj_set_align(ui_charging_speed_group, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_radius(ui_charging_speed_group, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charging_speed_group, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_charging_speed_group);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -21);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label12, "Current charging speed");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_Label12, 0);
    ui_group4 = lv_obj_create(ui_charging_speed_group);
    lv_obj_set_height(ui_group4, 60);
    lv_obj_set_width(ui_group4, lv_pct(44));
    lv_obj_set_x(ui_group4, 24);
    lv_obj_set_y(ui_group4, -4);
    lv_obj_set_align(ui_group4, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_group4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_group4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_group4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_group4);
    lv_obj_set_height(ui_Label13, 25);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label13, 6);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label13, "210");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_group4);
    lv_obj_set_height(ui_Label14, 12);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label14, -5);
    lv_obj_set_y(ui_Label14, 12);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "kW");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_group4, 1);
    ui_charge_bar_group = lv_obj_create(ui_content5);
    lv_obj_set_height(ui_charge_bar_group, 91);
    lv_obj_set_width(ui_charge_bar_group, lv_pct(116));
    lv_obj_set_x(ui_charge_bar_group, 0);
    lv_obj_set_y(ui_charge_bar_group, 42);
    lv_obj_set_align(ui_charge_bar_group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_charge_bar_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge_bar_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cardbg3 = ui_cardbg_create(ui_charge_bar_group);
    lv_obj_set_height(ui_cardbg3, 64);
    lv_obj_set_width(ui_cardbg3, lv_pct(96));
    lv_obj_set_x(ui_cardbg3, 0);
    lv_obj_set_y(ui_cardbg3, 1);
    lv_obj_set_align(ui_cardbg3, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_cardbg3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_cardbg3, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cardbg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cardbg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cardbg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cardbg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_anim_bg2 = lv_img_create(ui_cardbg3);
    lv_img_set_src(ui_anim_bg2, &ui_img_slider_bg2_png);
    lv_obj_set_width(ui_anim_bg2, lv_pct(150));
    lv_obj_set_height(ui_anim_bg2, lv_pct(100));
    lv_obj_set_align(ui_anim_bg2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_anim_bg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_anim_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_anim_bg2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_anim_bg2, 0);
    ui_anim_bg3 = lv_img_create(ui_cardbg3);
    lv_img_set_src(ui_anim_bg3, &ui_img_slider_bg3_png);
    lv_obj_set_width(ui_anim_bg3, lv_pct(150));
    lv_obj_set_height(ui_anim_bg3, lv_pct(100));
    lv_obj_set_align(ui_anim_bg3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_anim_bg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_anim_bg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_anim_bg3, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_anim_bg3, 1);
    ui_anim_bg1 = lv_img_create(ui_cardbg3);
    lv_img_set_src(ui_anim_bg1, &ui_img_slider_bg1_png);
    lv_obj_set_width(ui_anim_bg1, lv_pct(150));
    lv_obj_set_height(ui_anim_bg1, lv_pct(100));
    lv_obj_set_align(ui_anim_bg1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_anim_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_anim_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_anim_bg1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_anim_bg1, 2);
    ui_mask1 = lv_img_create(ui_cardbg3);
    lv_img_set_src(ui_mask1, &ui_img_slider_mask2_png);
    lv_obj_set_height(ui_mask1, 28);
    lv_obj_set_width(ui_mask1, lv_pct(100));
    lv_obj_set_x(ui_mask1, 0);
    lv_obj_set_y(ui_mask1, 1);
    lv_obj_set_align(ui_mask1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_mask1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mask1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_mask1, 3);
    ui_mask2 = lv_img_create(ui_cardbg3);
    lv_img_set_src(ui_mask2, &ui_img_slider_mask1_png);
    lv_obj_set_height(ui_mask2, 28);
    lv_obj_set_width(ui_mask2, lv_pct(100));
    lv_obj_set_x(ui_mask2, 3);
    lv_obj_set_y(ui_mask2, 1);
    lv_obj_set_align(ui_mask2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_mask2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mask2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_move_to_index(ui_mask2, 4);
    ui_charge_bar = lv_obj_create(ui_charge_bar_group);
    lv_obj_set_height(ui_charge_bar, 91);
    lv_obj_set_width(ui_charge_bar, lv_pct(96));
    lv_obj_set_align(ui_charge_bar, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_charge_bar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_charge_bar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_charge_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_charge_bar, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar = lv_obj_create(ui_charge_bar);
    lv_obj_set_width(ui_start_bar, 51);
    lv_obj_set_height(ui_start_bar, 95);
    lv_obj_set_x(ui_start_bar, 0);
    lv_obj_set_y(ui_start_bar, -38);
    lv_obj_set_align(ui_start_bar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_start_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar_indicator = lv_obj_create(ui_start_bar);
    lv_obj_set_height(ui_start_bar_indicator, 55);
    lv_obj_set_width(ui_start_bar_indicator, lv_pct(100));
    lv_obj_set_x(ui_start_bar_indicator, -1);
    lv_obj_set_y(ui_start_bar_indicator, -20);
    lv_obj_set_align(ui_start_bar_indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_start_bar_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_start_bar_indicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_start_bar_indicator, lv_color_hex(0x00B94C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_start_bar_indicator, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_start_bar_indicator, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_start_bar_indicator, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_start_bar_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_start_bar_indicator, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent = ui_percent_create(ui_start_bar);
    lv_obj_set_x(ui_percent, -1);
    lv_obj_set_y(ui_percent, 25);
    lv_obj_set_align(ui_percent, LV_ALIGN_CENTER);

    ui_charge_bar_indicator = lv_obj_create(ui_charge_bar);
    lv_obj_set_width(ui_charge_bar_indicator, 200);
    lv_obj_set_height(ui_charge_bar_indicator, 55);
    lv_obj_set_x(ui_charge_bar_indicator, -140);
    lv_obj_set_y(ui_charge_bar_indicator, 3);
    lv_obj_set_align(ui_charge_bar_indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_charge_bar_indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_charge_bar_indicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_charge_bar_indicator, lv_color_hex(0x0067D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_charge_bar_indicator, lv_color_hex(0x3FBDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_charge_bar_indicator, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_charge_bar_indicator, lv_color_hex(0x3FCFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_charge_bar_indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_charge_bar_indicator, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent_number1 = lv_label_create(ui_charge_bar_group);
    lv_obj_set_width(ui_percent_number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percent_number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percent_number1, 2);
    lv_obj_set_y(ui_percent_number1, -11);
    lv_obj_set_align(ui_percent_number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percent_number1, "54%");
    lv_obj_set_style_text_color(ui_percent_number1, lv_color_hex(0x111020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percent_number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percent_number1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent_number2 = lv_label_create(ui_charge_bar_group);
    lv_obj_set_width(ui_percent_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percent_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percent_number2, 0);
    lv_obj_set_y(ui_percent_number2, -12);
    lv_obj_set_align(ui_percent_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percent_number2, "54%");
    lv_obj_set_style_text_color(ui_percent_number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percent_number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percent_number2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent1 = ui_percent_create(ui_charge_bar_group);
    lv_obj_set_x(ui_percent1, 388);
    lv_obj_set_y(ui_percent1, 0);
    lv_obj_set_align(ui_percent1, LV_ALIGN_BOTTOM_LEFT);

    lv_obj_set_align(ui_comp_get_child(ui_percent1, UI_COMP_PERCENT_PERCENT_GROUP), LV_ALIGN_LEFT_MID);

    lv_label_set_text(ui_comp_get_child(ui_percent1, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), "80%");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_percent1, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL),
                               &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_align(ui_comp_get_child(ui_percent1, UI_COMP_PERCENT_CORNER), LV_ALIGN_TOP_LEFT);

    ui_Label16 = lv_label_create(ui_content5);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -17);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "State of charge");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_button5, ui_event_button5_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Charging, ui_event_Charging, LV_EVENT_ALL, NULL);

}

void ui_Charging_screen_destroy(void)
{
    if(ui_Charging) lv_obj_del(ui_Charging);

    // NULL screen variables
    ui_Charging = NULL;
    ui_content_group5 = NULL;
    ui_content5 = NULL;
    ui_info_group5 = NULL;
    ui_contact_icon5 = NULL;
    ui_call_number5 = NULL;
    ui_date5 = NULL;
    ui_button5 = NULL;
    ui_charging_time_group = NULL;
    ui_charging_tme = NULL;
    ui_Label1_charging = NULL;
    ui_group1 = NULL;
    ui_Label3_charging = NULL;
    ui_Label7 = NULL;
    ui_charging_cost_group = NULL;
    ui_charging_cost = NULL;
    ui_Label6 = NULL;
    ui_group2 = NULL;
    ui_Label8 = NULL;
    ui_charging_energie_group = NULL;
    ui_charging_energie = NULL;
    ui_Label9 = NULL;
    ui_group3 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_charging_speed_group = NULL;
    ui_Label12 = NULL;
    ui_group4 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_charge_bar_group = NULL;
    ui_cardbg3 = NULL;
    ui_anim_bg2 = NULL;
    ui_anim_bg3 = NULL;
    ui_anim_bg1 = NULL;
    ui_mask1 = NULL;
    ui_mask2 = NULL;
    ui_charge_bar = NULL;
    ui_start_bar = NULL;
    ui_start_bar_indicator = NULL;
    ui_percent = NULL;
    ui_charge_bar_indicator = NULL;
    ui_percent_number1 = NULL;
    ui_percent_number2 = NULL;
    ui_percent1 = NULL;
    ui_Label16 = NULL;

}
