// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_End = NULL;
lv_obj_t * ui_content_group6 = NULL;
lv_obj_t * ui_content6 = NULL;
lv_obj_t * ui_info_group6 = NULL;
lv_obj_t * ui_contact_icon6 = NULL;
lv_obj_t * ui_call_number6 = NULL;
lv_obj_t * ui_date6 = NULL;
lv_obj_t * ui_cardbg4 = NULL;
lv_obj_t * ui_fee_group4 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_fee_group3 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_summary_price = NULL;
lv_obj_t * ui_summary_price1 = NULL;
lv_obj_t * ui_charge_bar_group1 = NULL;
lv_obj_t * ui_cardbg1 = NULL;
lv_obj_t * ui_charge_bar1 = NULL;
lv_obj_t * ui_start_bar1 = NULL;
lv_obj_t * ui_start_bar_indicator1 = NULL;
lv_obj_t * ui_start_bar3 = NULL;
lv_obj_t * ui_charge_bar_indicator1 = NULL;
lv_obj_t * ui_percent4 = NULL;
lv_obj_t * ui_start_bar2 = NULL;
lv_obj_t * ui_start_bar_indicator2 = NULL;
lv_obj_t * ui_percent3 = NULL;
lv_obj_t * ui_Chart_group = NULL;
lv_obj_t * ui_chart_scrollbar = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_buttonGroup6 = NULL;
lv_obj_t * ui_button6 = NULL;
// event funtions
void ui_event_End(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_buttonGroup6, 0);
        top_on_Animation(ui_cardbg4, 100);
        end_bar_on_Animation(ui_charge_bar_group1, 100);
    }
}

void ui_event_button6_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Home_screen_init);
    }
}

// build funtions

void ui_End_screen_init(void)
{
    ui_End = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_End, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_End, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group6 = lv_obj_create(ui_End);
    lv_obj_set_width(ui_content_group6, lv_pct(100));
    lv_obj_set_height(ui_content_group6, lv_pct(100));
    lv_obj_set_align(ui_content_group6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content6 = lv_obj_create(ui_content_group6);
    lv_obj_set_height(ui_content6, lv_pct(100));
    lv_obj_set_flex_grow(ui_content6, 1);
    lv_obj_set_align(ui_content6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group6 = lv_obj_create(ui_content6);
    lv_obj_set_width(ui_info_group6, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_info_group6, -11);
    lv_obj_set_y(ui_info_group6, -15);
    lv_obj_set_flex_flow(ui_info_group6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_info_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon6 = lv_img_create(ui_info_group6);
    lv_img_set_src(ui_contact_icon6, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_contact_icon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number6 = lv_label_create(ui_info_group6);
    lv_obj_set_width(ui_call_number6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number6, "www.fusiontech.com.tw");
    lv_obj_set_style_text_color(ui_call_number6, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date6 = lv_label_create(ui_content6);
    lv_obj_set_width(ui_date6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date6, 21);
    lv_obj_set_y(ui_date6, -19);
    lv_obj_set_align(ui_date6, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date6, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_date6, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cardbg4 = ui_cardbg_create(ui_content6);
    lv_obj_set_width(ui_cardbg4, 185);
    lv_obj_set_height(ui_cardbg4, 147);
    lv_obj_set_x(ui_cardbg4, 19);
    lv_obj_set_y(ui_cardbg4, 4);
    lv_obj_set_align(ui_cardbg4, LV_ALIGN_TOP_RIGHT);

    ui_fee_group4 = lv_obj_create(ui_cardbg4);
    lv_obj_set_width(ui_fee_group4, 175);
    lv_obj_set_height(ui_fee_group4, 141);
    lv_obj_set_x(ui_fee_group4, -34);
    lv_obj_set_y(ui_fee_group4, 37);
    lv_obj_set_align(ui_fee_group4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_fee_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_fee_group4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 4);
    lv_obj_set_y(ui_Label18, 70);
    lv_label_set_text(ui_Label18, "Charging time");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_fee_group4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 9);
    lv_obj_set_y(ui_Label19, -11);
    lv_obj_set_align(ui_Label19, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label19, "53 min");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group4, 0);
    ui_fee_group3 = lv_obj_create(ui_cardbg4);
    lv_obj_set_width(ui_fee_group3, 174);
    lv_obj_set_height(ui_fee_group3, 130);
    lv_obj_set_x(ui_fee_group3, -31);
    lv_obj_set_y(ui_fee_group3, -35);
    lv_obj_clear_flag(ui_fee_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fee_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fee_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_fee_group3);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 2);
    lv_obj_set_y(ui_Label15, 4);
    lv_label_set_text(ui_Label15, "Total energy delivered");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_fee_group3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 4);
    lv_obj_set_y(ui_Label17, -67);
    lv_obj_set_align(ui_Label17, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label17, "87 kWh");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_fee_group3, 1);
    ui_summary_price = lv_label_create(ui_content6);
    lv_obj_set_width(ui_summary_price, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_summary_price, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_summary_price, -13);
    lv_obj_set_y(ui_summary_price, 75);
    lv_obj_set_align(ui_summary_price, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_summary_price, "$118");
    lv_obj_set_style_text_color(ui_summary_price, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_summary_price, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_summary_price, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_summary_price1 = lv_label_create(ui_content6);
    lv_obj_set_width(ui_summary_price1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_summary_price1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_summary_price1, -42);
    lv_obj_set_y(ui_summary_price1, 42);
    lv_obj_set_align(ui_summary_price1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_summary_price1, "Total session cost");
    lv_obj_set_style_text_color(ui_summary_price1, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_summary_price1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_summary_price1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge_bar_group1 = lv_obj_create(ui_content6);
    lv_obj_set_height(ui_charge_bar_group1, 62);
    lv_obj_set_width(ui_charge_bar_group1, lv_pct(79));
    lv_obj_set_x(ui_charge_bar_group1, -28);
    lv_obj_set_y(ui_charge_bar_group1, 27);
    lv_obj_set_align(ui_charge_bar_group1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_charge_bar_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge_bar_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_charge_bar_group1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charge_bar_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cardbg1 = ui_cardbg_create(ui_charge_bar_group1);
    lv_obj_set_height(ui_cardbg1, 28);
    lv_obj_set_width(ui_cardbg1, lv_pct(95));
    lv_obj_set_x(ui_cardbg1, -6);
    lv_obj_set_y(ui_cardbg1, 24);
    lv_obj_set_align(ui_cardbg1, LV_ALIGN_TOP_LEFT);
    lv_obj_set_style_radius(ui_cardbg1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_cardbg1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cardbg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge_bar1 = lv_obj_create(ui_charge_bar_group1);
    lv_obj_set_height(ui_charge_bar1, 164);
    lv_obj_set_width(ui_charge_bar1, lv_pct(95));
    lv_obj_set_x(ui_charge_bar1, -7);
    lv_obj_set_y(ui_charge_bar1, -47);
    lv_obj_clear_flag(ui_charge_bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_charge_bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_charge_bar1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar1 = lv_obj_create(ui_charge_bar1);
    lv_obj_set_width(ui_start_bar1, lv_pct(14));
    lv_obj_set_height(ui_start_bar1, LV_SIZE_CONTENT);    /// 255
    lv_obj_set_y(ui_start_bar1, 2);
    lv_obj_set_x(ui_start_bar1, lv_pct(-44));
    lv_obj_set_align(ui_start_bar1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_start_bar1, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_start_bar1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_start_bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar_indicator1 = lv_obj_create(ui_start_bar1);
    lv_obj_set_height(ui_start_bar_indicator1, 17);
    lv_obj_set_width(ui_start_bar_indicator1, lv_pct(100));
    lv_obj_set_x(ui_start_bar_indicator1, -63);
    lv_obj_set_y(ui_start_bar_indicator1, -46);
    lv_obj_clear_flag(ui_start_bar_indicator1, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_start_bar_indicator1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_start_bar_indicator1, lv_color_hex(0x00B94C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_start_bar_indicator1, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_start_bar_indicator1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_start_bar_indicator1, lv_color_hex(0x05FF6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_start_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_start_bar_indicator1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar3 = lv_obj_create(ui_charge_bar1);
    lv_obj_set_height(ui_start_bar3, 66);
    lv_obj_set_width(ui_start_bar3, lv_pct(62));
    lv_obj_set_x(ui_start_bar3, -14);
    lv_obj_set_y(ui_start_bar3, -9);
    lv_obj_set_align(ui_start_bar3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_start_bar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charge_bar_indicator1 = lv_obj_create(ui_start_bar3);
    lv_obj_set_height(ui_charge_bar_indicator1, 17);
    lv_obj_set_width(ui_charge_bar_indicator1, lv_pct(98));
    lv_obj_set_x(ui_charge_bar_indicator1, 0);
    lv_obj_set_y(ui_charge_bar_indicator1, 11);
    lv_obj_set_align(ui_charge_bar_indicator1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_charge_bar_indicator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_charge_bar_indicator1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_charge_bar_indicator1, lv_color_hex(0x0067D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_charge_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_charge_bar_indicator1, lv_color_hex(0x3FBDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_charge_bar_indicator1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_charge_bar_indicator1, lv_color_hex(0x3FCFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_charge_bar_indicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_charge_bar_indicator1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent4 = ui_percent_create(ui_start_bar3);
    lv_obj_set_width(ui_percent4, 118);
    lv_obj_set_height(ui_percent4, 27);
    lv_obj_set_x(ui_percent4, -25);
    lv_obj_set_y(ui_percent4, -19);
    lv_obj_set_style_layout(ui_percent4, 0, 0);

    lv_obj_set_width(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP), lv_pct(75));
    lv_obj_set_height(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP), lv_pct(100));
    lv_obj_set_align(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP), LV_ALIGN_TOP_LEFT);

    lv_obj_set_x(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), 0);
    lv_obj_set_y(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), 3);
    lv_label_set_text(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), "Start 15%");

    lv_obj_set_x(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_CORNER), 0);
    lv_obj_set_y(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_CORNER), 0);
    lv_obj_set_align(ui_comp_get_child(ui_percent4, UI_COMP_PERCENT_CORNER), LV_ALIGN_BOTTOM_LEFT);

    ui_start_bar2 = lv_obj_create(ui_charge_bar1);
    lv_obj_set_width(ui_start_bar2, 79);
    lv_obj_set_height(ui_start_bar2, LV_SIZE_CONTENT);    /// 255
    lv_obj_set_x(ui_start_bar2, 211);
    lv_obj_set_y(ui_start_bar2, 5);
    lv_obj_set_align(ui_start_bar2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_start_bar2, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_start_bar2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_start_bar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_start_bar2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_start_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start_bar_indicator2 = lv_obj_create(ui_start_bar2);
    lv_obj_set_height(ui_start_bar_indicator2, 47);
    lv_obj_set_width(ui_start_bar_indicator2, lv_pct(64));
    lv_obj_set_x(ui_start_bar_indicator2, -1);
    lv_obj_set_y(ui_start_bar_indicator2, -74);
    lv_obj_set_align(ui_start_bar_indicator2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_start_bar_indicator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_start_bar_indicator2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_start_bar_indicator2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percent3 = ui_percent_create(ui_start_bar2);
    lv_obj_set_height(ui_percent3, 25);
    lv_obj_set_width(ui_percent3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_x(ui_percent3, 0);
    lv_obj_set_y(ui_percent3, 0);

    lv_obj_set_width(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_PERCENT_GROUP), 75);
    lv_obj_set_height(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_PERCENT_GROUP), lv_pct(100));

    lv_label_set_text(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL), " Edn 80%");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_PERCENT_GROUP_PERCENT_LABEL),
                               &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_align(ui_comp_get_child(ui_percent3, UI_COMP_PERCENT_CORNER), LV_ALIGN_BOTTOM_LEFT);

    ui_Chart_group = lv_obj_create(ui_End);
    lv_obj_set_width(ui_Chart_group, 475);
    lv_obj_set_height(ui_Chart_group, 314);
    lv_obj_set_x(ui_Chart_group, 1);
    lv_obj_set_y(ui_Chart_group, 1);
    lv_obj_clear_flag(ui_Chart_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Chart_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chart_scrollbar = lv_obj_create(ui_Chart_group);
    lv_obj_set_width(ui_chart_scrollbar, 480);
    lv_obj_set_height(ui_chart_scrollbar, lv_pct(100));
    lv_obj_set_x(ui_chart_scrollbar, 2);
    lv_obj_set_y(ui_chart_scrollbar, 2);
    lv_obj_set_align(ui_chart_scrollbar, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_radius(ui_chart_scrollbar, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chart_scrollbar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_scrollbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chart_scrollbar, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chart_scrollbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chart_scrollbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chart_scrollbar, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_chart_scrollbar, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chart_scrollbar, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chart_scrollbar, 50, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chart_scrollbar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chart_scrollbar, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chart_scrollbar, 35, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_chart_scrollbar);
    lv_obj_set_height(ui_Chart2, 161);
    lv_obj_set_width(ui_Chart2, lv_pct(53));
    lv_obj_set_x(ui_Chart2, -4);
    lv_obj_set_y(ui_Chart2, -87);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_BOTTOM_LEFT);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 1, 100);
    lv_chart_set_div_line_count(ui_Chart2, 10, 10);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 11, 1, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x3BB7FC),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 3, 12, 20, 28, 36, 44, 48, 52, 57, 60, 64, 68, 70, 72, 75, 78, 80, 81, 82, 83, 84, 85 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0x252541), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Chart2, lv_color_hex(0x100F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Chart2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart2, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart2, lv_color_hex(0x22223D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Chart2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Chart2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Chart2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Chart2, true, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Chart2, 4, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart2, true, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Chart2, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Chart2, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Chart2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_Chart2, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x100F1F), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart2, lv_color_hex(0x19182D), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Chart_group);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 21);
    lv_obj_set_y(ui_Label21, -71);
    lv_obj_set_align(ui_Label21, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label21, "Time (min)");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x19182D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Chart_group);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 43);
    lv_obj_set_y(ui_Label22, 49);
    lv_label_set_text(ui_Label22, "Total energy delivered (kWh)");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonGroup6 = lv_obj_create(ui_End);
    lv_obj_set_width(ui_buttonGroup6, 134);
    lv_obj_set_height(ui_buttonGroup6, 309);
    lv_obj_set_x(ui_buttonGroup6, 154);
    lv_obj_set_y(ui_buttonGroup6, -4);
    lv_obj_set_align(ui_buttonGroup6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_buttonGroup6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonGroup6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonGroup6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button6 = ui_button_create(ui_buttonGroup6);
    lv_obj_set_width(ui_button6, 120);
    lv_obj_set_height(ui_button6, 45);
    lv_obj_set_x(ui_button6, 0);
    lv_obj_set_y(ui_button6, 125);
    lv_obj_set_align(ui_button6, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_button6, lv_color_hex(0x01D358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_button6, lv_color_hex(0x01D358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_button6, lv_color_hex(0x00B74B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_button6, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_label_set_text(ui_comp_get_child(ui_button6, UI_COMP_BUTTON_BUTTON_LABEL), "Finish");

    lv_obj_add_event_cb(ui_button6, ui_event_button6_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_End, ui_event_End, LV_EVENT_ALL, NULL);

}

void ui_End_screen_destroy(void)
{
    if(ui_End) lv_obj_del(ui_End);

    // NULL screen variables
    ui_End = NULL;
    ui_content_group6 = NULL;
    ui_content6 = NULL;
    ui_info_group6 = NULL;
    ui_contact_icon6 = NULL;
    ui_call_number6 = NULL;
    ui_date6 = NULL;
    ui_cardbg4 = NULL;
    ui_fee_group4 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_fee_group3 = NULL;
    ui_Label15 = NULL;
    ui_Label17 = NULL;
    ui_summary_price = NULL;
    ui_summary_price1 = NULL;
    ui_charge_bar_group1 = NULL;
    ui_cardbg1 = NULL;
    ui_charge_bar1 = NULL;
    ui_start_bar1 = NULL;
    ui_start_bar_indicator1 = NULL;
    ui_start_bar3 = NULL;
    ui_charge_bar_indicator1 = NULL;
    ui_percent4 = NULL;
    ui_start_bar2 = NULL;
    ui_start_bar_indicator2 = NULL;
    ui_percent3 = NULL;
    ui_Chart_group = NULL;
    ui_chart_scrollbar = NULL;
    ui_Chart2 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_buttonGroup6 = NULL;
    ui_button6 = NULL;

}
