// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);

extern void ui_event_menu_icon(lv_event_t * e);
extern void ui_event_button1_button(lv_event_t * e);
extern void ui_event_sw1(lv_event_t * e);
extern void ui_event_sw2(lv_event_t * e);
extern void ui_event_sw3(lv_event_t * e);
extern void ui_event_sw4(lv_event_t * e);
extern void ui_event_sw5(lv_event_t * e);
extern void ui_event_sw6(lv_event_t * e);

// === Home 主畫面 ===
extern lv_obj_t * ui_Home;

// === 頂部區域 (Top bar) ===
extern lv_obj_t * ui_topbar;     // 上方資訊列
extern lv_obj_t * ui_logo;       // 左上角 Logo Label/Image
extern lv_obj_t * ui_date;       // 日期
extern lv_obj_t * ui_time;       // 時間
extern lv_obj_t * ui_menu_icon;  // 右上角三條線 icon

// === 中間區域 (Scene Buttons) ===
extern lv_obj_t * ui_scene_group; // 場景按鈕群組
extern lv_obj_t * ui_scene1;
extern lv_obj_t * ui_scene2;
extern lv_obj_t * ui_scene3;
extern lv_obj_t * ui_scene4;
extern lv_obj_t * ui_scene5;
extern lv_obj_t * ui_scene6;
extern lv_obj_t * scene_label;
// === 底部區域 (Switch Buttons) ===
extern lv_obj_t * ui_switch_group; // 下方開關群組
extern lv_obj_t * ui_sw1;
extern lv_obj_t * ui_sw2;
extern lv_obj_t * ui_sw3;
extern lv_obj_t * ui_sw4;
extern lv_obj_t * ui_sw5;
extern lv_obj_t * ui_sw6;
extern lv_obj_t * ui_sw1_icon;
extern lv_obj_t * ui_sw1_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

