// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Step2 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_content_group3 = NULL;
lv_obj_t * ui_slidebar4 = NULL;
lv_obj_t * ui_icon_group7 = NULL;
lv_obj_t * ui_pricing_icon4 = NULL;
lv_obj_t * ui_pricing_label4 = NULL;
lv_obj_t * ui_icon_group5 = NULL;
lv_obj_t * ui_help_icon4 = NULL;
lv_obj_t * ui_help_label4 = NULL;
lv_obj_t * ui_content9 = NULL;
lv_obj_t * ui_info_group9 = NULL;
lv_obj_t * ui_contact_icon9 = NULL;
lv_obj_t * ui_call_number9 = NULL;
lv_obj_t * ui_date9 = NULL;
lv_obj_t * ui_charger_id3 = NULL;
lv_obj_t * ui_button_group3 = NULL;
lv_obj_t * ui_button9 = NULL;
lv_obj_t * ui_card2 = NULL;
lv_obj_t * ui_step_label2 = NULL;
lv_obj_t * ui_phone = NULL;
lv_obj_t * ui_QR_code = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_Step2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        bottom_on_Animation(ui_button9, 0);
        left_on_Animation(ui_card2, 0);
        phone_Animation(ui_phone, 0);
        top_on_Animation(ui_Image1, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_card2, 0);
        bottom_off_Animation(ui_phone, 100);
    }
}

void ui_event_button9_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Connect, LV_SCR_LOAD_ANIM_FADE_ON, 100, 200, &ui_Connect_screen_init);
    }
}

// build funtions

void ui_Step2_screen_init(void)
{
    ui_Step2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Step2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Step2, &ui_img_bg4_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Step2);
    lv_obj_set_width(ui_Label20, 253);
    lv_obj_set_height(ui_Label20, 56);
    lv_obj_set_x(ui_Label20, 9);
    lv_obj_set_y(ui_Label20, -60);
    lv_obj_set_align(ui_Label20, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label20,
                      "Please start your EV Charger application and scan this QR code to authenticate your device and set the payment method.");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content_group3 = lv_obj_create(ui_Step2);
    lv_obj_set_width(ui_content_group3, lv_pct(100));
    lv_obj_set_height(ui_content_group3, lv_pct(100));
    lv_obj_set_align(ui_content_group3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slidebar4 = lv_obj_create(ui_content_group3);
    lv_obj_set_width(ui_slidebar4, 50);
    lv_obj_set_height(ui_slidebar4, lv_pct(100));
    lv_obj_set_x(ui_slidebar4, 0);
    lv_obj_set_y(ui_slidebar4, -33);
    lv_obj_set_align(ui_slidebar4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_slidebar4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_slidebar4, &ui_img_left_side_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_slidebar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_slidebar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_slidebar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_slidebar4, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_slidebar4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_slidebar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group7 = lv_obj_create(ui_slidebar4);
    lv_obj_set_width(ui_icon_group7, 38);
    lv_obj_set_height(ui_icon_group7, 38);
    lv_obj_set_x(ui_icon_group7, 0);
    lv_obj_set_y(ui_icon_group7, 89);
    lv_obj_set_align(ui_icon_group7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_icon_group7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_icon_group7, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_icon_group7, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_icon_group7, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_pricing_icon4 = lv_img_create(ui_icon_group7);
    lv_img_set_src(ui_pricing_icon4, &ui_img_pricing_png);
    lv_obj_set_width(ui_pricing_icon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_icon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pricing_icon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pricing_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pricing_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pricing_label4 = lv_label_create(ui_icon_group7);
    lv_obj_set_width(ui_pricing_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pricing_label4, 8);
    lv_obj_set_y(ui_pricing_label4, 19);
    lv_obj_set_align(ui_pricing_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pricing_label4, "Pricing");
    lv_obj_set_style_text_color(ui_pricing_label4, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pricing_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pricing_label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group5 = lv_obj_create(ui_slidebar4);
    lv_obj_set_width(ui_icon_group5, 38);
    lv_obj_set_height(ui_icon_group5, 38);
    lv_obj_set_x(ui_icon_group5, 0);
    lv_obj_set_y(ui_icon_group5, 149);
    lv_obj_set_align(ui_icon_group5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_icon_group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_icon_group5, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_icon_group5, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_icon_group5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_help_icon4 = lv_img_create(ui_icon_group5);
    lv_img_set_src(ui_help_icon4, &ui_img_help_png);
    lv_obj_set_width(ui_help_icon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_icon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_icon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_help_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_help_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_help_label4 = lv_label_create(ui_icon_group5);
    lv_obj_set_width(ui_help_label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_help_label4, "Help");
    lv_obj_set_style_text_color(ui_help_label4, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_help_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_help_label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content9 = lv_obj_create(ui_content_group3);
    lv_obj_set_height(ui_content9, lv_pct(100));
    lv_obj_set_flex_grow(ui_content9, 1);
    lv_obj_set_align(ui_content9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group9 = lv_obj_create(ui_content9);
    lv_obj_set_width(ui_info_group9, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group9, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_info_group9, -23);
    lv_obj_set_y(ui_info_group9, -18);
    lv_obj_set_flex_flow(ui_info_group9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_info_group9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon9 = lv_img_create(ui_info_group9);
    lv_img_set_src(ui_contact_icon9, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_contact_icon9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_call_number9 = lv_label_create(ui_info_group9);
    lv_obj_set_width(ui_call_number9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number9, "www.fusiontech.com.tw");
    lv_obj_set_style_text_color(ui_call_number9, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date9 = lv_label_create(ui_content9);
    lv_obj_set_width(ui_date9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date9, 21);
    lv_obj_set_y(ui_date9, -18);
    lv_obj_set_align(ui_date9, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date9, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_date9, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charger_id3 = lv_label_create(ui_content9);
    lv_obj_set_width(ui_charger_id3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_charger_id3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_charger_id3, -20);
    lv_obj_set_y(ui_charger_id3, 18);
    lv_obj_set_align(ui_charger_id3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_charger_id3, "Charger #5879965-08");
    lv_obj_add_flag(ui_charger_id3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_charger_id3, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_charger_id3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_charger_id3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button_group3 = lv_obj_create(ui_content9);
    lv_obj_set_width(ui_button_group3, 480);
    lv_obj_set_height(ui_button_group3, 320);
    lv_obj_set_x(ui_button_group3, -20);
    lv_obj_set_y(ui_button_group3, 0);
    lv_obj_set_align(ui_button_group3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_button_group3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_button_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_button_group3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_button_group3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_button_group3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_button_group3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button9 = ui_button_create(ui_button_group3);
    lv_obj_set_width(ui_button9, 150);
    lv_obj_set_height(ui_button9, 40);
    lv_obj_set_x(ui_button9, 20);
    lv_obj_set_y(ui_button9, 18);
    lv_obj_set_align(ui_button9, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button9, UI_COMP_BUTTON_BUTTON_LABEL), "Next Step");

    ui_card2 = ui_card_create(ui_Step2);
    lv_obj_set_x(ui_card2, -100);
    lv_obj_set_y(ui_card2, -16);

    lv_obj_set_x(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_H), -31);
    lv_obj_set_y(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_H), 1);
    lv_label_set_text(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_H), "Authentication");

    lv_obj_set_x(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT), -28);
    lv_obj_set_y(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT), 29);
    lv_label_set_text(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "The first step is to plug the charger into thecar's charging port.\n");
    lv_obj_add_flag(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TEXT), LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_x(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TITLE), -5);
    lv_obj_set_y(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TITLE), -25);
    lv_label_set_text(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Step");

    ui_step_label2 = lv_label_create(ui_comp_get_child(ui_card2, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_step_label2, 20);
    lv_obj_set_height(ui_step_label2, 20);
    lv_obj_set_x(ui_step_label2, -32);
    lv_obj_set_y(ui_step_label2, -24);
    lv_label_set_text(ui_step_label2, "2");
    lv_obj_set_style_text_color(ui_step_label2, lv_color_hex(0x20203A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_step_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_step_label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_step_label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_step_label2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_step_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_step_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_step_label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_step_label2, 3);
    ui_phone = lv_img_create(ui_Step2);
    lv_img_set_src(ui_phone, &ui_img_phone_png);
    lv_obj_set_width(ui_phone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phone, -50);
    lv_obj_set_y(ui_phone, 0);
    lv_obj_set_align(ui_phone, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_phone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_phone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_QR_code = lv_obj_create(ui_Step2);
    lv_obj_set_width(ui_QR_code, 130);
    lv_obj_set_height(ui_QR_code, 238);
    lv_obj_set_x(ui_QR_code, 124);
    lv_obj_set_y(ui_QR_code, -111);
    lv_obj_set_align(ui_QR_code, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_QR_code, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_QR_code, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QR_code, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_QR_code);
    lv_img_set_src(ui_Image1, &ui_img_qr_code1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 176
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 176
    lv_obj_set_x(ui_Image1, -4);
    lv_obj_set_y(ui_Image1, 22);
    lv_obj_set_align(ui_Image1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_button9, ui_event_button9_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Step2, ui_event_Step2, LV_EVENT_ALL, NULL);

}

void ui_Step2_screen_destroy(void)
{
    if(ui_Step2) lv_obj_del(ui_Step2);

    // NULL screen variables
    ui_Step2 = NULL;
    ui_Label20 = NULL;
    ui_content_group3 = NULL;
    ui_slidebar4 = NULL;
    ui_icon_group7 = NULL;
    ui_pricing_icon4 = NULL;
    ui_pricing_label4 = NULL;
    ui_icon_group5 = NULL;
    ui_help_icon4 = NULL;
    ui_help_label4 = NULL;
    ui_content9 = NULL;
    ui_info_group9 = NULL;
    ui_contact_icon9 = NULL;
    ui_call_number9 = NULL;
    ui_date9 = NULL;
    ui_charger_id3 = NULL;
    ui_button_group3 = NULL;
    ui_button9 = NULL;
    ui_card2 = NULL;
    ui_step_label2 = NULL;
    ui_phone = NULL;
    ui_QR_code = NULL;
    ui_Image1 = NULL;

}
