// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: A_Meter_GUI_20240305

#include "../ui.h"

lv_obj_t * ui_SC_LOGO =NULL;
lv_obj_t * ui_Lab_ID =NULL;
lv_obj_t * ui_Lab_Ver =NULL;
lv_obj_t * ui_Panel1 =NULL;
lv_obj_t * ui_Label177 =NULL;
lv_obj_t * ui_ui_Label2 =NULL;
void ui_SC_LOGO_screen_init(void)
{
    ui_SC_LOGO = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SC_LOGO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SC_LOGO, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lab_ID = lv_label_create(ui_SC_LOGO);
    lv_obj_set_width(ui_Lab_ID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lab_ID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lab_ID, 100);
    lv_obj_set_y(ui_Lab_ID, 36);
    lv_obj_set_align(ui_Lab_ID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lab_ID, "");
    lv_obj_set_style_text_color(ui_Lab_ID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lab_ID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Lab_ID, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lab_ID, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lab_Ver = lv_label_create(ui_SC_LOGO);
    lv_obj_set_width(ui_Lab_Ver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lab_Ver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lab_Ver, 81);
    lv_obj_set_y(ui_Lab_Ver, 77);
    lv_obj_set_align(ui_Lab_Ver, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lab_Ver, "");
    lv_obj_set_style_text_color(ui_Lab_Ver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lab_Ver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Lab_Ver, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lab_Ver, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_SC_LOGO);
    //lv_img_set_src(ui_Image2, &ui_img_logo_png);
    lv_img_set_src(ui_Image2, &ui_img_contact_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 277
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 107
    lv_obj_set_x(ui_Image2, 4);
    lv_obj_set_y(ui_Image2, -46);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_SC_LOGO);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 3458);
    lv_obj_set_y(ui_Panel1, 12);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label177 = lv_label_create(ui_SC_LOGO);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -53);
    lv_obj_set_y(ui_Label17, 77);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Ver.");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_SC_LOGO);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -53);
    lv_obj_set_y(ui_Label2, 36);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "     PK100 Camera Demo");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2,&lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    

}
