// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#include "../ui.h"

lv_obj_t * ui_Step1 = NULL;
lv_obj_t * ui_light = NULL;
lv_obj_t * ui_content_group2 = NULL;
lv_obj_t * ui_slidebar2 = NULL;
lv_obj_t * ui_icon_group3 = NULL;
lv_obj_t * ui_pricing_icon2 = NULL;
lv_obj_t * ui_pricing_label2 = NULL;
lv_obj_t * ui_icon_group4 = NULL;
lv_obj_t * ui_help_icon2 = NULL;
lv_obj_t * ui_help_label2 = NULL;
lv_obj_t * ui_content2 = NULL;
lv_obj_t * ui_info_group2 = NULL;
lv_obj_t * ui_contact_icon2 = NULL;
lv_obj_t * ui_call_number2 = NULL;
lv_obj_t * ui_date3 = NULL;
lv_obj_t * ui_charger_id2 = NULL;
lv_obj_t * ui_card1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_button_group2 = NULL;
lv_obj_t * ui_button2 = NULL;
// event funtions
void ui_event_Step1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        left_on_Animation(ui_card1, 0);
        bottom_on_Animation(ui_button2, 0);
        light_Animation(ui_light, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        left_off_Animation(ui_card1, 0);
    }
}

void ui_event_button2_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_Step1_screen_init(void)
{
    ui_Step1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Step1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Step1, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light = lv_img_create(ui_Step1);
    lv_img_set_src(ui_light, &ui_img_light_png);
    lv_obj_set_width(ui_light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light, 139);
    lv_obj_set_y(ui_light, -9);
    lv_obj_set_align(ui_light, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_content_group2 = lv_obj_create(ui_Step1);
    lv_obj_set_width(ui_content_group2, lv_pct(100));
    lv_obj_set_height(ui_content_group2, lv_pct(100));
    lv_obj_set_align(ui_content_group2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_content_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_content_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_content_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slidebar2 = lv_obj_create(ui_content_group2);
    lv_obj_set_width(ui_slidebar2, 50);
    lv_obj_set_height(ui_slidebar2, lv_pct(100));
    lv_obj_set_x(ui_slidebar2, 0);
    lv_obj_set_y(ui_slidebar2, -33);
    lv_obj_set_align(ui_slidebar2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_slidebar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_slidebar2, &ui_img_left_side_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_slidebar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_slidebar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_slidebar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_slidebar2, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_slidebar2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_slidebar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group3 = lv_obj_create(ui_slidebar2);
    lv_obj_set_width(ui_icon_group3, 38);
    lv_obj_set_height(ui_icon_group3, 38);
    lv_obj_set_x(ui_icon_group3, 0);
    lv_obj_set_y(ui_icon_group3, 89);
    lv_obj_set_align(ui_icon_group3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_icon_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_icon_group3, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_icon_group3, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_icon_group3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_pricing_icon2 = lv_img_create(ui_icon_group3);
    lv_img_set_src(ui_pricing_icon2, &ui_img_pricing_png);
    lv_obj_set_width(ui_pricing_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pricing_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pricing_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pricing_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_pricing_icon2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_pricing_icon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pricing_label2 = lv_label_create(ui_icon_group3);
    lv_obj_set_width(ui_pricing_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pricing_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pricing_label2, 8);
    lv_obj_set_y(ui_pricing_label2, 19);
    lv_obj_set_align(ui_pricing_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pricing_label2, "Pricing");
    lv_obj_set_style_text_color(ui_pricing_label2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pricing_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pricing_label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon_group4 = lv_obj_create(ui_slidebar2);
    lv_obj_set_width(ui_icon_group4, 38);
    lv_obj_set_height(ui_icon_group4, 38);
    lv_obj_set_x(ui_icon_group4, 0);
    lv_obj_set_y(ui_icon_group4, 149);
    lv_obj_set_align(ui_icon_group4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_icon_group4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_icon_group4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_icon_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_icon_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_icon_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_icon_group4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_icon_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_icon_group4, 12, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_icon_group4, lv_color_hex(0x22223C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_icon_group4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_help_icon2 = lv_img_create(ui_icon_group4);
    lv_img_set_src(ui_help_icon2, &ui_img_help_png);
    lv_obj_set_width(ui_help_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_help_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_help_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_help_label2 = lv_label_create(ui_icon_group4);
    lv_obj_set_width(ui_help_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_help_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_help_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_help_label2, "Help");
    lv_obj_set_style_text_color(ui_help_label2, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_help_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_help_label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_content2 = lv_obj_create(ui_content_group2);
    lv_obj_set_height(ui_content2, lv_pct(100));
    lv_obj_set_flex_grow(ui_content2, 1);
    lv_obj_set_align(ui_content2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_content2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_content2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_content2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info_group2 = lv_obj_create(ui_content2);
    lv_obj_set_width(ui_info_group2, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_info_group2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_info_group2, -23);
    lv_obj_set_y(ui_info_group2, -18);
    lv_obj_set_flex_flow(ui_info_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_info_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_info_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_info_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_info_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_info_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contact_icon2 = lv_img_create(ui_info_group2);
    lv_img_set_src(ui_contact_icon2, &ui_img_contact_png);
    lv_obj_set_width(ui_contact_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contact_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_contact_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contact_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_contact_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_contact_icon2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_contact_icon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_call_number2 = lv_label_create(ui_info_group2);
    lv_obj_set_width(ui_call_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_call_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_call_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_call_number2, "www.fusiontech.com.tw");
    lv_obj_set_style_text_color(ui_call_number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_call_number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_call_number2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date3 = lv_label_create(ui_content2);
    lv_obj_set_width(ui_date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date3, 21);
    lv_obj_set_y(ui_date3, -18);
    lv_obj_set_align(ui_date3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_date3, "01.03.2023. 14:49 PM");
    lv_obj_set_style_text_color(ui_date3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_charger_id2 = lv_label_create(ui_content2);
    lv_obj_set_width(ui_charger_id2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_charger_id2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_charger_id2, -20);
    lv_obj_set_y(ui_charger_id2, 18);
    lv_obj_set_align(ui_charger_id2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_charger_id2, "Charger #5879965-08");
    lv_obj_set_style_text_color(ui_charger_id2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_charger_id2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_charger_id2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_card1 = ui_card_create(ui_Step1);
    lv_obj_set_x(ui_card1, -100);
    lv_obj_set_y(ui_card1, -16);

    lv_obj_set_x(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_H), -18);
    lv_obj_set_y(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_H), 4);
    lv_label_set_text(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_H), "Plug in first");

    lv_obj_set_x(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_TEXT), -30);
    lv_obj_set_y(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_TEXT), 35);
    lv_label_set_text(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_TEXT),
                      "The first step is to plug the charger into the car's charging port.");

    lv_obj_set_x(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_TITLE), -5);
    lv_obj_set_y(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_TITLE), -25);
    lv_label_set_text(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2_CARD_TITLE), "Step");

    ui_Label2 = lv_label_create(ui_comp_get_child(ui_card1, UI_COMP_CARD_CARDBG2));
    lv_obj_set_width(ui_Label2, 20);
    lv_obj_set_height(ui_Label2, 20);
    lv_obj_set_x(ui_Label2, -32);
    lv_obj_set_y(ui_Label2, -24);
    lv_label_set_text(ui_Label2, "1");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x20203A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_move_to_index(ui_Label2, 3);
    ui_button_group2 = lv_obj_create(ui_Step1);
    lv_obj_set_width(ui_button_group2, lv_pct(100));
    lv_obj_set_height(ui_button_group2, lv_pct(100));
    lv_obj_set_x(ui_button_group2, 1);
    lv_obj_set_y(ui_button_group2, 0);
    lv_obj_set_align(ui_button_group2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_button_group2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_button_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_button_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_button_group2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_button_group2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_button_group2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_button_group2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_button2 = ui_button_create(ui_button_group2);
    lv_obj_set_width(ui_button2, 150);
    lv_obj_set_height(ui_button2, 40);
    lv_obj_set_x(ui_button2, 20);
    lv_obj_set_y(ui_button2, 18);
    lv_obj_set_align(ui_button2, LV_ALIGN_BOTTOM_RIGHT);

    lv_label_set_text(ui_comp_get_child(ui_button2, UI_COMP_BUTTON_BUTTON_LABEL), "Next Step");

    lv_obj_add_event_cb(ui_button2, ui_event_button2_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Step1, ui_event_Step1, LV_EVENT_ALL, NULL);

}

void ui_Step1_screen_destroy(void)
{
    if(ui_Step1) lv_obj_del(ui_Step1);

    // NULL screen variables
    ui_Step1 = NULL;
    ui_light = NULL;
    ui_content_group2 = NULL;
    ui_slidebar2 = NULL;
    ui_icon_group3 = NULL;
    ui_pricing_icon2 = NULL;
    ui_pricing_label2 = NULL;
    ui_icon_group4 = NULL;
    ui_help_icon2 = NULL;
    ui_help_label2 = NULL;
    ui_content2 = NULL;
    ui_info_group2 = NULL;
    ui_contact_icon2 = NULL;
    ui_call_number2 = NULL;
    ui_date3 = NULL;
    ui_charger_id2 = NULL;
    ui_card1 = NULL;
    ui_Label2 = NULL;
    ui_button_group2 = NULL;
    ui_button2 = NULL;

}
