// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#ifndef UI_STEP2_H
#define UI_STEP2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Step2
extern void ui_Step2_screen_init(void);
extern void ui_Step2_screen_destroy(void);
extern void ui_event_Step2(lv_event_t * e);
extern lv_obj_t * ui_Step2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_content_group3;
extern lv_obj_t * ui_slidebar4;
extern lv_obj_t * ui_icon_group7;
extern lv_obj_t * ui_pricing_icon4;
extern lv_obj_t * ui_pricing_label4;
extern lv_obj_t * ui_icon_group5;
extern lv_obj_t * ui_help_icon4;
extern lv_obj_t * ui_help_label4;
extern lv_obj_t * ui_content9;
extern lv_obj_t * ui_info_group9;
extern lv_obj_t * ui_contact_icon9;
extern lv_obj_t * ui_call_number9;
extern lv_obj_t * ui_date9;
extern lv_obj_t * ui_charger_id3;
extern lv_obj_t * ui_button_group3;
extern void ui_event_button9_button(lv_event_t * e);
extern lv_obj_t * ui_button9;
extern lv_obj_t * ui_card2;
extern lv_obj_t * ui_step_label2;
extern lv_obj_t * ui_phone;
extern lv_obj_t * ui_QR_code;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

