// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: EV_Charger

#ifndef _EV_CHARGER_UI_H
#define _EV_CHARGER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"
#include "screens/ui_Step1.h"
#include "screens/ui_Step2.h"
#include "screens/ui_Connect.h"
#include "screens/ui_Welcome.h"
#include "screens/ui_Charging.h"
#include "screens/ui_End.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * charging1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * charging2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * charging3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * left_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * left_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bottom_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bottom_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * phone_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * big_left_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ready_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ready_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * top_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * end_bar_on_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * end_bar_off_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * light_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_left_side_png);    // assets/left_side.png
LV_IMG_DECLARE(ui_img_pricing_png);    // assets/pricing.png
LV_IMG_DECLARE(ui_img_help_png);    // assets/help.png
LV_IMG_DECLARE(ui_img_contact_png);    // assets/contact.png
LV_IMG_DECLARE(ui_img_s1_car_png);    // assets/s1_car.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png
LV_IMG_DECLARE(ui_img_bg4_png);    // assets/bg4.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_qr_code1_png);    // assets/qr_code1.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png
LV_IMG_DECLARE(ui_img_slider_bg2_png);    // assets/slider_bg2.png
LV_IMG_DECLARE(ui_img_slider_bg3_png);    // assets/slider_bg3.png
LV_IMG_DECLARE(ui_img_slider_bg1_png);    // assets/slider_bg1.png
LV_IMG_DECLARE(ui_img_slider_mask2_png);    // assets/slider_mask2.png
LV_IMG_DECLARE(ui_img_slider_mask1_png);    // assets/slider_mask1.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
